
"use client";

import { Card, CardContent } from "@/components/ui/card";
import { FileText } from "lucide-react";

export default function TermsOfServicePage() {

  return (
    <main className="flex-1 flex flex-col items-center justify-start p-4 sm:p-6 md:p-8">
      <div className="w-full max-w-4xl">
        <Card>
          <CardContent className="prose dark:prose-invert max-w-none p-6 sm:p-8">
            <div className="not-prose mb-8">
              <h1 className="text-3xl font-bold flex items-center gap-2 mb-2">
                <FileText className="h-8 w-8 text-primary" />
                Terms of Service
              </h1>
              <p className="text-muted-foreground">Last Updated: August 1, 2024</p>
            </div>
            
            <p>
              Please read these Terms of Service ("Terms") carefully before using the EduGenius AI application (the "Service"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
            </p>
            
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
            </p>
            
            <h2>2. Description of Service</h2>
            <p>
              EduGenius AI provides tools to generate educational materials, including question papers, gradesheets, and ID cards ("Content"). The Service utilizes both manual data entry and third-party artificial intelligence models for Content generation. All data and Content are stored locally on the user's device.
            </p>

            <h2>3. User Responsibilities</h2>
            <ul>
              <li>You are responsible for the accuracy of the data you input into the Service.</li>
              <li>You agree not to input any personally identifiable information (PII) that is sensitive or protected by data privacy laws (e.g., social security numbers, health information) into the forms, especially into fields that are sent to third-party AI services.</li>
              <li>You are responsible for reviewing and validating all Content generated by the Service, including AI-generated questions, for accuracy, appropriateness, and completeness before use.</li>
            </ul>

            <h2>4. AI-Generated Content Disclaimer</h2>
            <p>
              The Content generated by artificial intelligence is probabilistic and may contain inaccuracies, biases, or errors. EduGenius AI does not guarantee the accuracy, reliability, or suitability of AI-generated Content. It is intended as a draft or a starting point. The final responsibility for the published or used Content lies with you, the user.
            </p>

            <h2>5. Intellectual Property</h2>
            <p>
              You retain all ownership rights to the Content you create using the Service. We retain all ownership rights to the Service itself, including the user interface, design, and underlying code.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              In no event shall EduGenius AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your use of the Service or the Content created by it. The Service is provided on an "AS IS" and "AS AVAILABLE" basis.
            </p>

            <h2>7. Termination</h2>
            <p>
              We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
            </p>

            <h2>8. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which the company is based, without regard to its conflict of law provisions.
            </p>
            
            <h2>9. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.
            </p>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
